-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDbnk0ao3l5gkcnXo
p4DaWwuGqOTKIuErl+dThdGbd9OgCgYIKoZIzj0DAQehRANCAARBBAP8axklXaUe
heaPjnVQU23VViGwtMTGEYDDDuyri5O7XiHGPBnb2oxvBI52y5kX8Y0FxeLXgn4J
nQ5WBNwg
-----END PRIVATE KEY-----