[package]
name = "check-if-email-exists"
version = "0.9.1"
authors = ["Amaury <amaury@reacher.email>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check-if-email-exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "verification"]
license = "AGPL-3.0"
publish = true
readme = "../README.md"
repository = "https://github.com/reacherhq/check-if-email-exists"

[dependencies]
async-native-tls = { version = "0.4", default-features = false }
async-recursion = "1.0.0"
async-smtp = { version = "0.5.0", features = ["socks5"] }
async-std = "1.12.0"
async-std-resolver = "0.21.2"
fantoccini = { version = "0.19.3", optional = true }
futures = { version = "0.3.24", optional = true  }
fast-socks5 = "0.8.1"
log = "0.4.17"
mailchecker = "5.0.0"
rand = {version = "0.8.5", features = ["small_rng"] }
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["json", "socks"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
trust-dns-proto = "0.21.2"

[dev-dependencies]
tokio = { version = "1.21.0" }

[features]
headless = ["fantoccini", "futures"]
